feat: add ethToWant
yearn/brownie-strategy-mix pull request #41
Opened 2021-04-12 13:07 UTC by steffenix

target version 0.4.0

2021-05-17 13:55 UTC, fubuloubu commented on contracts/Strategy.sol
> +    {}
There should be no default to force downstream users to override this.
```suggestion
    function ethToWant(uint256 _amtInWei) public view virtual returns (uint256);
```

2021-05-17 13:56 UTC, fubuloubu requested changes

2021-05-17 13:56 UTC, fubuloubu commented on contracts/Strategy.sol
> +    {}
```suggestion
    {
        return _amtInWei; // TODO: Override this with an accurate oracle price
    }
```

2021-05-17 15:31 UTC, fubuloubu approved these changes

2021-05-18 06:51 UTC, steffenix commented
closed in favor of https://github.com/yearn/brownie-strategy-mix/pull/45

2021-05-18 06:51 UTC, closed without merging